docs/_include/general-shipping/replace-placeholders-prometheus.html, docs/_include/metric-shipping/telegraf-setup.md, docs/shipping/active-directory.md, docs/shipping/aerospike.md
=> Henn back updates jul31

_manifest/manifest_generator.py, _manifest/readme.md
- Adjust manifest to handle new docs structure (sub-folders).
- Add url encode to file path, to work as a link.
=> Manifest generator - handle new sub folders

docs/_include/log-shipping/add-s3-bucket.md, docs/shipping/AWS/aws-cloudtrail.md, docs/shipping/AWS/aws-lambda.md, docs/shipping/AWS/aws-s3-access.md
=> adding spaces and titles

docs/_include/tracing-shipping/docker.md
https://deploy-preview-163--shiny-alfajores-ede8d8.netlify.app/docs/shipping/Code/Node-js#traces
=> checking include inside include

docs/_include/tracing-shipping/docker.md
Reverts logzio/documentation#163
=> Revert "checking include inside include"

docs/_include/tracing-shipping/docker.md
inside {@include: ../../_include/tracing-shipping/docker.md}
=> Separate include

docs/user-guide/telemetry-collector/cloud-fetcher.md
https://deploy-preview-172--shiny-alfajores-ede8d8.netlify.app/docs/user-guide/telemetry-collector/cloud-fetcher
=> Cloud fetcher

docs/user-guide/quick-start.md
https://deploy-preview-214--shiny-alfajores-ede8d8.netlify.app/docs/user-guide/quick-start
=> Quick start - New images

docs/_include/log-shipping/apprunner-defaults.md, docs/_include/log-shipping/cloudwatch-defaults.md, docs/_include/tracing-shipping/dotnet-framework-steps.md, docs/_include/tracing-shipping/dotnet-steps.md, docs/shipping/Code/node-js.md
=> changing ``` languages

docs/shipping/Code/dotnet.md
- Log4net serverless section
- NLog serverless section
- LoggerFactory serverless section
- SeriLog serverless section
=> Add serverless docs

docs/user-guide/admin/account-volume-optimization/manage-account-usage.md
https://deploy-preview-234--shiny-alfajores-ede8d8.netlify.app/docs/user-guide/admin/account-volume-optimization/manage-account-usage
=> Manage accounts - adding values

docs/shipping/AWS/kinesis.md
Reverts logzio/documentation#276
=> Revert "Removing deprecated integration"

docs/shipping/Code/java.md
https://deploy-preview-292--shiny-alfajores-ede8d8.netlify.app/docs/shipping/code/java/#metrics
=> Java - adding space

docs/user-guide/cloud-siem/quick-guide/create-jira-ticket-alert.md
https://deploy-preview-295--shiny-alfajores-ede8d8.netlify.app/docs/user-guide/cloud-siem/quick-guide/create-jira-ticket-alert/#:~:text=Enter%20the%20following%20header
=> Jira tickets - adding =

docs/user-guide/data-hub/archive-restore/set-s3-permissions.md
https://deploy-preview-306--shiny-alfajores-ede8d8.netlify.app/docs/user-guide/data-hub/archive-restore/set-s3-permissions#add-power-search-permissions
=> Add permissions

docs/user-guide/data-hub/archive-restore/restore-archived-logs.md
/docs/user-guide/data-hub/archive-restore/set-s3-permissions/#add-power-search-permissions
=> More links

docs/user-guide/data-hub/sampling-rules.md
https://deploy-preview-369--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/data-hub/sampling-rules/
=> Sampling rule - adding note

docs/shipping/Other/fluentd.md
https://deploy-preview-402--deluxe-empanada-3ebf3b.netlify.app/docs/shipping/other/fluentd-data/#check-logzio-for-your-logs
=> Multiline - adding more context

docs/user-guide/admin/sso/sso-main-sub-accounts.md
https://deploy-preview-406--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/admin/sso/sso-main-sub-accounts/
=> Note about sso

docs/shipping/AWS/aws-s3-bucket.md, yarn.lock
https://docs.logz.io/docs/shipping/aws/aws-s3-bucket/#shipping-logs-via-s3-hook
=> Fix broken link

docs/shipping/AWS/aws-s3-bucket.md
https://deploy-preview-409--deluxe-empanada-3ebf3b.netlify.app/docs/shipping/aws/aws-s3-bucket/#shipping-logs-via-s3-fetcher
=> S3 - new links

static/_redirects
https://deploy-preview-410--deluxe-empanada-3ebf3b.netlify.app/getting-started.html
=> Fixing broken link

docs/shipping/AWS/aws-s3-bucket.md
https://deploy-preview-411--deluxe-empanada-3ebf3b.netlify.app/docs/shipping/aws/aws-s3-bucket/
=> Adding dots

docs/shipping/AWS/aws-s3-bucket.md
https://deploy-preview-412--deluxe-empanada-3ebf3b.netlify.app/docs/shipping/aws/aws-s3-bucket/
=> Adding outside link

docs/shipping/AWS/aws-s3-bucket.md
Reverts logzio/documentation#412
=> Revert "Adding outside link"

docs/user-guide/telemetry-collector/telemetry-collector-localhost.md
https://deploy-preview-420--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/telemetry-collector/telemetry-collector-localhost/
=> Collector note

docs/user-guide/data-hub/archive-restore/restore-archived-logs.md
https://deploy-preview-424--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/data-hub/archive-restore/restore-archived-logs/
=> Restore archived logs - updating note

docs/shipping/Azure/azure-activity-logs.md, docs/shipping/Azure/azure-diagnostic-logs.md
A migration from Classic Application Insights to Log Analytics Workspace guide.
=> Migration to Log Analytics Workspace

docs/shipping/Azure/azure-diagnostic-logs.md
Updated the services list that gets deploy
=> updated services that gets deploy

docs/user-guide/new-explore.md
https://deploy-preview-452--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/explore/meet-explore/
=> New explore

docs/user-guide/distributed-tracing/navigating-tracing/compare-traces.md
/docs/user-guide/distributed-tracing/navigating-tracing/compare-traces
=> Tests - Hiding page

docs/user-guide/distributed-tracing/navigating-tracing/compare-traces.md
Reverts logzio/documentation#455
=> Revert "Tests - Hiding page"

docs/user-guide/data-hub/logstometrics.md
https://deploy-preview-462--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/data-hub/logstometrics/#configure-logmetrics
=> LogMetrics - adding note

docs/user-guide/explore/_category_.json, docs/user-guide/explore/new-explore.md
https://deploy-preview-463--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/new-explore/
=> Explore - new screenshots

docs/user-guide/explore/new-explore.md
https://deploy-preview-474--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/new-explore/
=> Explore screenshot edits

docs/user-guide/k8s-360/kubernetes-360-pre.md
https://deploy-preview-491--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/k8s-360/kubernetes-360-pre#additional-kubernetes-metrics
=> K8s - more labels

docs/_include/general-shipping/k8s-all-data.md, docs/_include/general-shipping/k8s.md
Deploy metrics chart with Kuberenetes object logs correlation
=> Add Kubernetes object logs

docs/user-guide/observability/faq.md
https://deploy-preview-522--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/observability/faq
=> Updating IQ faq

docs/_include/tracing-shipping/collector-config.md, docs/_include/tracing-shipping/docker.md, docs/shipping/Other/opentelemetry.md
Add user agent header for OpenTelemetry docs
=> add user agent header for opentelemetry

docs/shipping/Code/go.md
Reverts logzio/documentation#540
=> Revert "testing"

docs/shipping/AWS/aws-lambda-extensions.md
- Update ARNs with new lambda version
- Add the env variable `JSON_FIELDS_UNDER_ROOT`
=> update logzio-lambda-extensions-logs version

docs/user-guide/explore/new-explore.md
https://deploy-preview-551--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/new-explore/
=> Explore favs

docs/user-guide/data-hub/drop-filters/drop-fiters-logs.md
https://deploy-preview-561--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/data-hub/drop-filters/drop-fiters-logs
=> Drop log tip

docs/user-guide/data-hub/log-parsing/sawmill-parsing.md, docs/user-guide/quick-start.md
https://deploy-preview-576--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/data-hub/log-parsing/sawmill-parsing
=> DIY Parsing shut down note

docs/user-guide/explore/new-explore.md
https://deploy-preview-581--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/new-explore/
=> explore updates

docs/shipping/GCP/gcp-workspace.md, docs/user-guide/data-hub/archive-restore/azure-blob-permissions.md
https://deploy-preview-579--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/data-hub/archive-restore/azure-blob-permissions/#allowlist-ips-per-region
https://deploy-preview-579--deluxe-empanada-3ebf3b.netlify.app/docs/shipping/GCP/GCP-Workspace
=> Docs updates jul22

docs/user-guide/log-management/cold-tier.md
https://deploy-preview-598--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/log-management/cold-tier/
=> Cold tier note

docs/_include/general-shipping/k8s-all-data.md, docs/_include/general-shipping/k8s.md, docs/user-guide/k8s-360/unified-helm-chart.md
For some reason the `{@include: ../../_include/general-shipping/k8s-all-data.md}` section as well as "Manual Setup" header are missing in the Send your data page
=> try fix the missing all telemetry command from send your data

docs/shipping/Code/dotnet.md, docs/shipping/Code/java.md
=> Testing toc

docs/user-guide/explore/troubleshooting/invalid-log-errors.md, docs/user-guide/log-management/troubleshooting/understanding-invalid-log-errors.md
https://deploy-preview-637--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/log-management/troubleshooting/understanding-invalid-log-errors/
=> Adding note about inavlid

docs/user-guide/log-management/log-alerts/alert-shortcuts.md
https://deploy-preview-639--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/log-management/log-alerts/alert-shortcuts
=> Alert - insights update

docs/user-guide/cloud-siem/integrations/create-jira-ticket-alert.md
https://deploy-preview-640--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/cloud-siem/integrations/create-jira-ticket-alert/
=> Editing json

docs/user-guide/data-hub/log-parsing/split-json-array.md
https://deploy-preview-655--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/data-hub/log-parsing/split-json-array
=> Nested objects

docs/shipping/Access-Management/jumpcloud.md
Added support for org_id header in JumpCloud API
=> Added org_id option

docs/shipping/Containers/docker.md
https://deploy-preview-709--deluxe-empanada-3ebf3b.netlify.app/docs/shipping/containers/docker/
=> Docker - adding a tab

docs/user-guide/observability/assistantiq.md
https://deploy-preview-711--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/observability/assistantiq/
=> No go no pro

docs/user-guide/admin/hosting-regions/account-region.md
/docs/user-guide/admin/hosting-regions/account-region/
=> OTLP regions

docs/shipping/Code/node-js.md
=> fixing note

docs/shipping/Code/java-traces-with-kafka-using-opentelemetry.md, docs/shipping/Code/java.md
https://logzio.atlassian.net/browse/DOC-887
=> removing some otlp

docs/shipping/Code/go.md
- Fix the Go SDK OTEL Tracing example
=> Go SDK OTEL Tracing fix

docs/shipping/AWS/aws-ec2.md, docs/shipping/AWS/aws-ecs-fargate.md, docs/shipping/App360/App360.md, docs/shipping/Operating-Systems/windows.md, docs/shipping/Other/consul.md
https://deploy-preview-735--deluxe-empanada-3ebf3b.netlify.app/docs/shipping/App360/#create-the-config-file
=> Editing config file section

docs/shipping/Code/go.md
/docs/shipping/code/go/#metrics
=> nested metrics

docs/user-guide/observability/assistantiq.md
https://deploy-preview-730--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/observability/assistantiq/
=> ai agent rca

docs/_include/general-shipping/data-shipping-tokens_vars.md, docs/user-guide/admin/authentication-tokens/finding-your-metrics-account-token.md
https://deploy-preview-731--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/admin/authentication-tokens/finding-your-metrics-account-token/
=> Adding note about token

docs/user-guide/cloud-siem/dashboards.md
https://deploy-preview-733--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/cloud-siem/dashboards/#configuring-visualizations-for-siem-rules
=> Siem - visualize rules

docs/shipping/Network/cloudflare.md, docs/user-guide/log-management/api-fetcher.md
https://deploy-preview-737--deluxe-empanada-3ebf3b.netlify.app/docs/shipping/network/cloudflare-network/
=> Remove account id

docs/shipping/AWS/aws-eks.md
https://deploy-preview-760--deluxe-empanada-3ebf3b.netlify.app/docs/shipping/aws/aws-eks/#send-your-metrics
=> ECS metrics - adding note

docs/shipping/AWS/aws-lambda-extensions.md
https://deploy-preview-775--deluxe-empanada-3ebf3b.netlify.app/docs/shipping/aws/lambda-extensions/#prerequisites
=> updating link

docs/shipping/Code/go.md
Update Go module versioning conventions for version 2.0.0
=> Go Metrics SDK Release v2.0.0

docs/user-guide/admin/consumption.md
https://deploy-preview-787--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/admin/consumption/
=> Consumption

docs/_include/general-shipping/k8s.md, docs/user-guide/k8s-360/unified-helm-chart.md
Following meeting with CS groups:
- add how to enable debug mode explanation for OTEL operator
=> add debug mode explanation for OTEL operator

docs/shipping/AWS/aws-eks.md, docs/shipping/Code/dotnet-traces-kafka.md, docs/shipping/Code/java-traces-with-kafka-using-opentelemetry.md, docs/shipping/Code/nestjs.md, docs/shipping/Code/node-js.md, docs/shipping/Code/python.md, docs/shipping/Code/ruby.md, docs/shipping/Orchestration/istio-traces.md, docs/shipping/Security/trivy.md
following call with customer, looks like some of the docs pages are not updated with the helm command required for monitoring v7
=> Align all pages helm commands to monitoring v7

docs/shipping/GCP/gcp-workspace.md, docs/shipping/Network/cloudflare.md, docs/shipping/Security/one-password.md, docs/user-guide/log-management/api-fetcher.md
- Add the new google workspace API guide
- Add explanation on using multiple Logz.io API outputs
=> Update docs with new api fetcher features

docs/_include/general-shipping/k8s.md, docs/shipping/Containers/kubernetes.md, static/_redirects
Reverts logzio/documentation#816
=> Revert "edits"

docs/_include/general-shipping/k8s.md, docs/shipping/Containers/kubernetes.md, docs/user-guide/k8s-360/unified-helm-chart.md
logzio-monitoring 7.2.0 introduces the ability to add global tolerations to all subcharts. @Simplychee I added a section in k8s.md, please let me know if we need to add it also somewhere else
=> Adding Global Tolerations k8s

docs/_include/general-shipping/k8s.md, docs/user-guide/k8s-360/unified-helm-chart.md
- Split advanced configuration from troubleshooting section
- add resource detection explanation
=> Update K8s helm advanced configuration

docs/user-guide/integrations/terraform.md
https://deploy-preview-834--deluxe-empanada-3ebf3b.netlify.app/docs/integrations/terraform/
=> terraform note

docs/user-guide/explore/troubleshooting/invalid-log-errors.md
https://deploy-preview-833--deluxe-empanada-3ebf3b.netlify.app/docs/user-guide/log-management/troubleshooting/understanding-invalid-log-errors/
=> Truncate updates

docs/user-guide/admin/account-volume-optimization/manage-account-usage.md, docs/user-guide/cloud-siem/quick-guide/create-rules.md, docs/user-guide/cloud-siem/security-rules/manage-security-rules.md, docs/user-guide/explore/explore-log-alerts/configure-alerts-explore.md, docs/user-guide/log-management/collaboration/collaboration.md, docs/user-guide/log-management/collaboration/sharing-links.md, docs/user-guide/log-management/log-alerts/configure-alert.md, docs/user-guide/log-management/reports.md
https://docs.logz.io/docs/user-guide/admin/account-volume-optimization/manage-account-usage/
https://docs.logz.io/docs/user-guide/cloud-siem/quick-guide/create-rules/
https://docs.logz.io/docs/user-guide/log-management/reports/
https://docs.logz.io/docs/user-guide/cloud-siem/quick-guide/edit-rules/
https://docs.logz.io/docs/user-guide/log-management/collaboration/
http://docs.logz.io/docs/user-guide/log-management/collaboration/sharing-links/
https://docs.logz.io/docs/user-guide/explore/explore-log-alerts/configure-alerts-explore/
https://docs.logz.io/docs/user-guide/log-management/log-alerts/configure-alert/
=> snapshots limitation
